### ISSUE TITLE
Openpnm; calculating of permeability using io.statoil

### ISSUE THREAD

**Issue by saeidabd** [saeidabd/saeed-abd#1]
Dear  @jgostick
I am using io.statoil to import a Network (called S1 in [here](https://www.imperial.ac.uk/earth-science/research/research-groups/perm/research/pore-scale-modelling/micro-ct-images-and-networks/sandstone-s1/) in imperial college) in openpnm. I run a StokesFlow algorithm and used calc_effective_permeability but the value of permeability is much more bigger than permebility they report or exist in the literatures. I'm confused, what's the problem? what should I do?

**Comment by saeidabd** [comment]
`import openpnm as op
import numpy as np
import scipy as sp
from pathlib import Path
#importing network and geometry from S1----------------------------------------
path=Path('C:\\Users\\saeed\\Desktop\\Network_S1')
project = op.io.Statoil.load(path=path, prefix='S1')
pn = project.network
cordNUM=pn.num_neighbors(pores=pn.Ps)
print('Coordination number: ',np.sum(cordNUM)/pn.Np)
#trimming [nan] pores and throats
net_health = pn.check_network_health()
h = pn.check_network_health()
op.topotools.trim(network=pn, pores=h['trim_pores'])
print(pn)
pn['pore.diameter'] = 2*pn['pore.radius']
pn['throat.diameter'] = 2*pn['throat.radius']
#phases------------------------------------------------------------------------
water = op.phases.Water(network=pn)
pn['pore.diameter'] = 2*pn['pore.radius']
pn['throat.diameter'] = 2*pn['throat.radius']
#physics-----------------------------------------------------------------------
pn.add_model(propname='pore.area',
              model=op.models.geometry.pore_area.sphere)
pn.add_model(propname='throat.area',
              model=op.models.geometry.throat_area.cylinder)
pn.add_model(propname='throat.endpoints',
              model=op.models.geometry.throat_endpoints.spherical_pores)
pn.add_model(propname='throat.conduit_lengths',
              model=op.models.geometry.throat_length.conduit_lengths)
water.add_model(propname='throat.hydraulic_conductance',
                  model=op.models.physics.hydraulic_conductance.hagen_poiseuille)
#algorithms---------------------------------------------------------------------
flow = op.algorithms.StokesFlow(network=pn, phase=water)
flow.set_value_BC(pores=pn.pores('inlets'), values=200000)
flow.set_value_BC(pores=pn.pores('outlets'), values=100000)
flow.run()
mu = sp.mean(water['pore.viscosity'])
delta_P = 100000
# Because we know the inlets and outlets are at x=0 and x=X
Lx = sp.amax(pn['pore.coords'][:, 0]) 
porevolume=sp.sum(pn['pore.volume'])
th_volume=sp.sum(pn['throat.volume'])
V_pore=porevolume+th_volume
Porosity=V_pore/((Lx)**3)*100
print('Porosity:' , Porosity, '%')
domain_area=[]
for i in pn.pores('inlets'):
    domain_area.append(pn['pore.area'][i])
domain_area=sp.sum(domain_area)
Keff=flow.calc_effective_permeability(inlets=pn.pores('inlets'),
                                 outlets=pn.pores('outlets'),domain_area=domain_area,
                                 domain_length=Lx)
print('effective Permeability:',Keff/0.98e-15 , 'mD')
`

**Comment by saeidabd** [comment]
openpnm get the k about 10841 md but imperial guys report it about 1500 md.

**Comment by jgostick** [comment]
Hi Saeid
Normally you should open your issue on the openpnm repo instead of you own, but this works I guess.  Anyway, try this example: 

https://github.com/PMEAL/OpenPNM/blob/dev/examples/simulations/BereaSandstone%20Effective-Permeability.ipynb

Let me know if you still have trouble.

**Comment by saeidabd** [comment]
Thanks for your quick replying. I usually respond quick but we have internet connection problems in Tehran, Iran for couple of days (as we still have). You are right, I will write it in the OpenPNM repo next time. 
It generally seems ok but I have problem for importing the berea files example you said use [this link ](https://www.imperial.ac.uk/earth-science/research/research-groups/perm/research/pore-scale-modelling/micro-ct-images-and-networks/berea-sandstone/) generating by Martin Blunt et al. There are .raw and .dat files but openpnm needs a tif one. I try to transform the format of .raw but it didn't work correctly in openpnm as it cannot show the confirming plot show (imshow) and openpnm in the following went to running loop so I force python to stop it. what's your suggestion? which of them should I use?

**Comment by jgostick** [comment]
You are getting mixed up about "network extraction" and "importing a network".  In the first case, you can use PoreSpy which has the SNOW network extraction algorithm ([examples here](https://github.com/PMEAL/porespy/tree/master/examples/networks)).  This can then be opened in OpenPNM easily as described in the linked examples.  In the second case, it's for when you've used Blunts code to do an extraction and have the result in their 'statoil' format.

**Comment by saeidabd** [comment]
> You are getting mixed up about "network extraction" and "importing a network". In the first case, you can use PoreSpy which has the SNOW network extraction algorithm ([examples here](https://github.com/PMEAL/porespy/tree/master/examples/networks)). This can then be opened in OpenPNM easily as described in the linked examples. In the second case, it's for when you've used Blunts code to do an extraction and have the result in their 'statoil' format.

Thank you very much. Relative Permeability value makes sense. I will close the issue.
